[package]
name = "event-stream"
description = "Simple message passing library for Rust"
version = "0.1.1"
authors = ["robin <r@ansvia.com>"]
edition = "2018"
license = "MIT"

[dependencies]
crossbeam-channel = "0.3"
